// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/faas/v1/faas.proto

package io.nitric.proto.faas.v1;

public interface ApiWorkerOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.faas.v1.ApiWorkerOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Apply security definitions to this operation
   * </pre>
   *
   * <code>repeated string security = 1;</code>
   * @return A list containing the security.
   */
  java.util.List<java.lang.String>
      getSecurityList();
  /**
   * <pre>
   * Apply security definitions to this operation
   * </pre>
   *
   * <code>repeated string security = 1;</code>
   * @return The count of security.
   */
  int getSecurityCount();
  /**
   * <pre>
   * Apply security definitions to this operation
   * </pre>
   *
   * <code>repeated string security = 1;</code>
   * @param index The index of the element to return.
   * @return The security at the given index.
   */
  java.lang.String getSecurity(int index);
  /**
   * <pre>
   * Apply security definitions to this operation
   * </pre>
   *
   * <code>repeated string security = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the security at the given index.
   */
  com.google.protobuf.ByteString
      getSecurityBytes(int index);

  /**
   * <pre>
   * explicitly disable security for this endpoint
   * We need to do this as the default value of a repeated field
   * is always empty so there is no way of knowing if security is explicitly disabled
   * </pre>
   *
   * <code>bool security_disabled = 2;</code>
   * @return The securityDisabled.
   */
  boolean getSecurityDisabled();
}
