// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/faas/v1/faas.proto

package io.nitric.proto.faas.v1;

public interface ApiWorkerOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.faas.v1.ApiWorkerOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Apply the api level security definition
   * to this route
   * </pre>
   *
   * <code>string security_definition = 1;</code>
   * @return The securityDefinition.
   */
  java.lang.String getSecurityDefinition();
  /**
   * <pre>
   * Apply the api level security definition
   * to this route
   * </pre>
   *
   * <code>string security_definition = 1;</code>
   * @return The bytes for securityDefinition.
   */
  com.google.protobuf.ByteString
      getSecurityDefinitionBytes();
}
